# parse_python_exception